cc_library(
    name = "mq",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    features = ["warnings_critical_code_gcc"],
    visibility = ["//visibility:public"],
    deps = [
        "@cppzmq",
    ],
)
