cc_library(
    name = "can",
    srcs = ["CanDriver.cpp"],
    hdrs = ["CanDriver.hpp"],
    features = ["warnings_critical_code_gcc"],
    visibility = ["//visibility:public"],
    deps = ["//com-middleware/exceptions"],
)
