cc_library(
    name = "can",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    features = ["warnings_critical_code_gcc"],
    visibility = ["//visibility:public"],
    deps = ["//com-middleware/src/exceptions"],
)
