load("//bazel/rules:qt.bzl", "qt_resource")

package(default_visibility = ["//visibility:public"])

qt_resource(
    name = "constants",
    files = [
        "Constants.qml",
        "qmldir",
    ],
)
