cc_library(
    name = "exceptions",
    srcs = glob(
        ["*.cpp"],
        allow_empty = True,
    ),
    hdrs = glob(["*.hpp"]),
    features = ["warnings_critical_code_gcc"],
    visibility = ["//visibility:public"],
)
