load("//bazel/rules:qt.bzl", "qt_resource")

package(default_visibility = ["//visibility:public"])

qt_resource(
    name = "components",
    files = [
        "CircularSlider.qml",
        "ClusterWidget.qml",
        "Speedometer.qml",
        "Tachometer.qml",
        "qmldir",
    ],
)
