load("@py_deps//:requirements.bzl", "requirement")

py_binary(
    name = "lcov_compare",
    srcs = [
        "__init__.py",
        "lcov_compare.py",
    ],
    deps = [
        requirement("tabulate"),
    ],
)
