load("@py_deps//:requirements.bzl", "requirement")

py_library(
    name = "coordinate_transformer_lib",
    srcs = [
        "__init__.py",
        "coordinate_transformer.py",
    ],
    imports = ["."],
    deps = [
        requirement("numpy"),
    ],
)
