---
name: Bazel Build
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Bazel build
        run: |-
          bazel build //...
