# yamllint disable rule:line-length
---
name: Clang-Tidy
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['*']

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: dtors/base-cpp:latest

    steps:
      - name: Set safe directory for Git
        run: git config --global --add safe.directory /__w/Team04/Team04

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find affected files
        id: affected_files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }} > affected_files.txt
          echo "Affected files:"
          cat affected_files.txt

      - name: Find affected cpp files
        id: bazel_targets
        run: |
          > affected_cpp_files.txt

          while read file; do
            if [[ "$file" == *.cpp || "$file" == *.h || "$file" == *.hpp || "$file" == *.cc || "$file" == *.cxx || "$file" == *.hxx ]]; then
              echo "$file" >> affected_cpp_files.txt
            fi
          done < affected_files.txt

          sort -u affected_cpp_files.txt -o affected_cpp_files.txt
          echo "Affected cpp files:"
          cat affected_cpp_files.txt

          echo "cpp_files=$(cat affected_cpp_files.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Generate Compile Commands
        if: env.cpp_files != ''
        run: |
          echo "Generating compile commands"
          bazel run @hedron_compile_commands//:refresh_all

      - name: Running Clang-Tidy
        if: env.cpp_files != ''
        run: |
          > clang_tidy_output.txt

          echo "Running Clang-Tidy for: ${cpp_files}"
          clang-tidy ${cpp_files} -p ./compile_commands.json -header-filter=.* -system-headers > clang_tidy_output.txt

      - name: Filter Clang-Tidy Output
        if: env.cpp_files != ''
        run: |
          grep -E "$(echo $cpp_files | sed 's/ /|/g')" clang_tidy_output.txt > filtered-output.txt
          cat filtered-output.txt
          echo "clang_tidy_findings=$(cat affected_targets.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Skip Clang-Tidy
        if: env.cpp_files == ''
        run: echo "No affected cpp files found. Skipping Clang-Tidy."

      - name: Skip Clang-Tidy
        if: env.clang_tidy_findings == ''
        run: echo "No clang-tidy findings."

      - name: Show failure message
        if: failure()
        run: |-
          echo -e "To automatically apply suggested fixes, run the following command:
          ======================================================================================
          1. Generate compile commands:
          bazel run @hedron_compile_commands//:refresh_all
          2. Run clang-tidy:
          find . -name \"*.cpp\" -o -name \"*.h\" -o -name \"*.hpp\" -o -name \"*.cc\" -o -name \"*.cxx\" -o -name \"*.hxx\" | xargs clang-tidy -fix -fix-errors -p ./compile_commands.json --system-headers=0
          ======================================================================================"
