# yamllint disable rule:line-length
---
name: Coverage
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['*']

jobs:
  lcov:
    runs-on: ubuntu-latest
    container:
      image: t4seame/app:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Coverage Script
        run: bazelisk run //tools/coverage:lcov --platforms=//bazel/platforms:x86_64_linux -- -t :unit_tests
        shell: bash
