---
name: GitLint
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['*']
jobs:
  gitlint:
    runs-on: ubuntu-latest
    container:
      image: dtors/base-cpp:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Configure Git Safe Directory
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Run gitlint
        run: |-
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD"
