---
name: Run llvm-cov
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['*']

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install LLVM
        run: |
          sudo apt update
          sudo apt install -y llvm

      - name: Run Coverage Script
        run: bazel run //tools/coverage:llvm_cov -- -t //examples/cpp:test -s
