# yamllint disable rule:line-length
---
name: Release
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: t4seame/app:latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for rebase

      - name: Configure Git Safe Directory
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Fetch main branch
        run: |
          git fetch origin main

      - name: Rebase PR branch onto main
        run: |
          git rebase origin/main || (git rebase --abort && exit 1)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            - Commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Build for aarch64
        run: bazel build //:release_bins --platforms=//bazel/platforms:aarch64_linux

      - name: Upload Release arm64 bins
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bazel-out/k8-fastbuild/bin/release_bins.tar.gz
          asset_name: aarch64_bins.tar.gz
          asset_content_type: application/gzip

      - name: Build for x86_64
        run: bazel build //:release_bins --platforms=//bazel/platforms:x86_64_linux

      - name: Upload Release arm64 bins
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bazel-out/k8-fastbuild/bin/release_bins.tar.gz
          asset_name: x86_64_bins.tar.gz
          asset_content_type: application/gzip
